//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ModelQLDKDL", "FK_tChuyenDuLich_MaTuyen", "tTuyen", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QLDL.tTuyen), "tChuyenDuLich", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QLDL.tChuyenDuLich), true)]
[assembly: EdmRelationshipAttribute("ModelQLDKDL", "FK_tDangKy_MaChuyen", "tChuyenDuLich", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QLDL.tChuyenDuLich), "tDangKy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QLDL.tDangKy), true)]
[assembly: EdmRelationshipAttribute("ModelQLDKDL", "FK_tDangKy_MaKhach", "tKhach", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QLDL.tKhach), "tDangKy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QLDL.tDangKy), true)]
[assembly: EdmRelationshipAttribute("ModelQLDKDL", "tChiTietTuyenDuLich", "tChuyenDuLich", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QLDL.tChuyenDuLich), "tDiaDiemThamQuan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QLDL.tDiaDiemThamQuan))]

#endregion

namespace QLDL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelQLDKDLContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelQLDKDLContainer object using the connection string found in the 'ModelQLDKDLContainer' section of the application configuration file.
        /// </summary>
        public ModelQLDKDLContainer() : base("name=ModelQLDKDLContainer", "ModelQLDKDLContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelQLDKDLContainer object.
        /// </summary>
        public ModelQLDKDLContainer(string connectionString) : base(connectionString, "ModelQLDKDLContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelQLDKDLContainer object.
        /// </summary>
        public ModelQLDKDLContainer(EntityConnection connection) : base(connection, "ModelQLDKDLContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tChuyenDuLich> tChuyenDuLich
        {
            get
            {
                if ((_tChuyenDuLich == null))
                {
                    _tChuyenDuLich = base.CreateObjectSet<tChuyenDuLich>("tChuyenDuLich");
                }
                return _tChuyenDuLich;
            }
        }
        private ObjectSet<tChuyenDuLich> _tChuyenDuLich;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tDangKy> tDangKy
        {
            get
            {
                if ((_tDangKy == null))
                {
                    _tDangKy = base.CreateObjectSet<tDangKy>("tDangKy");
                }
                return _tDangKy;
            }
        }
        private ObjectSet<tDangKy> _tDangKy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tDiaDiemThamQuan> tDiaDiemThamQuan
        {
            get
            {
                if ((_tDiaDiemThamQuan == null))
                {
                    _tDiaDiemThamQuan = base.CreateObjectSet<tDiaDiemThamQuan>("tDiaDiemThamQuan");
                }
                return _tDiaDiemThamQuan;
            }
        }
        private ObjectSet<tDiaDiemThamQuan> _tDiaDiemThamQuan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tKhach> tKhach
        {
            get
            {
                if ((_tKhach == null))
                {
                    _tKhach = base.CreateObjectSet<tKhach>("tKhach");
                }
                return _tKhach;
            }
        }
        private ObjectSet<tKhach> _tKhach;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tTuyen> tTuyen
        {
            get
            {
                if ((_tTuyen == null))
                {
                    _tTuyen = base.CreateObjectSet<tTuyen>("tTuyen");
                }
                return _tTuyen;
            }
        }
        private ObjectSet<tTuyen> _tTuyen;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tChuyenDuLich EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotChuyenDuLich(tChuyenDuLich tChuyenDuLich)
        {
            base.AddObject("tChuyenDuLich", tChuyenDuLich);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tDangKy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotDangKy(tDangKy tDangKy)
        {
            base.AddObject("tDangKy", tDangKy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tDiaDiemThamQuan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotDiaDiemThamQuan(tDiaDiemThamQuan tDiaDiemThamQuan)
        {
            base.AddObject("tDiaDiemThamQuan", tDiaDiemThamQuan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tKhach EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotKhach(tKhach tKhach)
        {
            base.AddObject("tKhach", tKhach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tTuyen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotTuyen(tTuyen tTuyen)
        {
            base.AddObject("tTuyen", tTuyen);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelQLDKDL", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelQLDKDL", Name="tChuyenDuLich")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tChuyenDuLich : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tChuyenDuLich object.
        /// </summary>
        /// <param name="maChuyen">Initial value of the MaChuyen property.</param>
        /// <param name="maTuyen">Initial value of the MaTuyen property.</param>
        public static tChuyenDuLich CreatetChuyenDuLich(global::System.String maChuyen, global::System.String maTuyen)
        {
            tChuyenDuLich tChuyenDuLich = new tChuyenDuLich();
            tChuyenDuLich.MaChuyen = maChuyen;
            tChuyenDuLich.MaTuyen = maTuyen;
            return tChuyenDuLich;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaChuyen
        {
            get
            {
                return _MaChuyen;
            }
            set
            {
                if (_MaChuyen != value)
                {
                    OnMaChuyenChanging(value);
                    ReportPropertyChanging("MaChuyen");
                    _MaChuyen = StructuralObject.SetValidValue(value, false, "MaChuyen");
                    ReportPropertyChanged("MaChuyen");
                    OnMaChuyenChanged();
                }
            }
        }
        private global::System.String _MaChuyen;
        partial void OnMaChuyenChanging(global::System.String value);
        partial void OnMaChuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaTuyen
        {
            get
            {
                return _MaTuyen;
            }
            set
            {
                OnMaTuyenChanging(value);
                ReportPropertyChanging("MaTuyen");
                _MaTuyen = StructuralObject.SetValidValue(value, false, "MaTuyen");
                ReportPropertyChanged("MaTuyen");
                OnMaTuyenChanged();
            }
        }
        private global::System.String _MaTuyen;
        partial void OnMaTuyenChanging(global::System.String value);
        partial void OnMaTuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhuongTien
        {
            get
            {
                return _PhuongTien;
            }
            set
            {
                OnPhuongTienChanging(value);
                ReportPropertyChanging("PhuongTien");
                _PhuongTien = StructuralObject.SetValidValue(value, true, "PhuongTien");
                ReportPropertyChanged("PhuongTien");
                OnPhuongTienChanged();
            }
        }
        private global::System.String _PhuongTien;
        partial void OnPhuongTienChanging(global::System.String value);
        partial void OnPhuongTienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenHDVien
        {
            get
            {
                return _TenHDVien;
            }
            set
            {
                OnTenHDVienChanging(value);
                ReportPropertyChanging("TenHDVien");
                _TenHDVien = StructuralObject.SetValidValue(value, true, "TenHDVien");
                ReportPropertyChanged("TenHDVien");
                OnTenHDVienChanged();
            }
        }
        private global::System.String _TenHDVien;
        partial void OnTenHDVienChanging(global::System.String value);
        partial void OnTenHDVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DonGia
        {
            get
            {
                return _DonGia;
            }
            set
            {
                OnDonGiaChanging(value);
                ReportPropertyChanging("DonGia");
                _DonGia = StructuralObject.SetValidValue(value, "DonGia");
                ReportPropertyChanged("DonGia");
                OnDonGiaChanged();
            }
        }
        private Nullable<global::System.Double> _DonGia;
        partial void OnDonGiaChanging(Nullable<global::System.Double> value);
        partial void OnDonGiaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "FK_tChuyenDuLich_MaTuyen", "tTuyen")]
        public tTuyen tTuyen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tTuyen>("ModelQLDKDL.FK_tChuyenDuLich_MaTuyen", "tTuyen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tTuyen>("ModelQLDKDL.FK_tChuyenDuLich_MaTuyen", "tTuyen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tTuyen> tTuyenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tTuyen>("ModelQLDKDL.FK_tChuyenDuLich_MaTuyen", "tTuyen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tTuyen>("ModelQLDKDL.FK_tChuyenDuLich_MaTuyen", "tTuyen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "FK_tDangKy_MaChuyen", "tDangKy")]
        public EntityCollection<tDangKy> tDangKy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tDangKy>("ModelQLDKDL.FK_tDangKy_MaChuyen", "tDangKy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tDangKy>("ModelQLDKDL.FK_tDangKy_MaChuyen", "tDangKy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "tChiTietTuyenDuLich", "tDiaDiemThamQuan")]
        public EntityCollection<tDiaDiemThamQuan> tDiaDiemThamQuan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tDiaDiemThamQuan>("ModelQLDKDL.tChiTietTuyenDuLich", "tDiaDiemThamQuan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tDiaDiemThamQuan>("ModelQLDKDL.tChiTietTuyenDuLich", "tDiaDiemThamQuan", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelQLDKDL", Name="tDangKy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tDangKy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tDangKy object.
        /// </summary>
        /// <param name="maChuyen">Initial value of the MaChuyen property.</param>
        /// <param name="maKhach">Initial value of the MaKhach property.</param>
        public static tDangKy CreatetDangKy(global::System.String maChuyen, global::System.String maKhach)
        {
            tDangKy tDangKy = new tDangKy();
            tDangKy.MaChuyen = maChuyen;
            tDangKy.MaKhach = maKhach;
            return tDangKy;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaChuyen
        {
            get
            {
                return _MaChuyen;
            }
            set
            {
                if (_MaChuyen != value)
                {
                    OnMaChuyenChanging(value);
                    ReportPropertyChanging("MaChuyen");
                    _MaChuyen = StructuralObject.SetValidValue(value, false, "MaChuyen");
                    ReportPropertyChanged("MaChuyen");
                    OnMaChuyenChanged();
                }
            }
        }
        private global::System.String _MaChuyen;
        partial void OnMaChuyenChanging(global::System.String value);
        partial void OnMaChuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaKhach
        {
            get
            {
                return _MaKhach;
            }
            set
            {
                if (_MaKhach != value)
                {
                    OnMaKhachChanging(value);
                    ReportPropertyChanging("MaKhach");
                    _MaKhach = StructuralObject.SetValidValue(value, false, "MaKhach");
                    ReportPropertyChanged("MaKhach");
                    OnMaKhachChanged();
                }
            }
        }
        private global::System.String _MaKhach;
        partial void OnMaKhachChanging(global::System.String value);
        partial void OnMaKhachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayDKy
        {
            get
            {
                return _NgayDKy;
            }
            set
            {
                OnNgayDKyChanging(value);
                ReportPropertyChanging("NgayDKy");
                _NgayDKy = StructuralObject.SetValidValue(value, "NgayDKy");
                ReportPropertyChanged("NgayDKy");
                OnNgayDKyChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayDKy;
        partial void OnNgayDKyChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayDKyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> STDTra
        {
            get
            {
                return _STDTra;
            }
            set
            {
                OnSTDTraChanging(value);
                ReportPropertyChanging("STDTra");
                _STDTra = StructuralObject.SetValidValue(value, "STDTra");
                ReportPropertyChanged("STDTra");
                OnSTDTraChanged();
            }
        }
        private Nullable<global::System.Double> _STDTra;
        partial void OnSTDTraChanging(Nullable<global::System.Double> value);
        partial void OnSTDTraChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "FK_tDangKy_MaChuyen", "tChuyenDuLich")]
        public tChuyenDuLich tChuyenDuLich
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tChuyenDuLich>("ModelQLDKDL.FK_tDangKy_MaChuyen", "tChuyenDuLich").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tChuyenDuLich>("ModelQLDKDL.FK_tDangKy_MaChuyen", "tChuyenDuLich").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tChuyenDuLich> tChuyenDuLichReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tChuyenDuLich>("ModelQLDKDL.FK_tDangKy_MaChuyen", "tChuyenDuLich");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tChuyenDuLich>("ModelQLDKDL.FK_tDangKy_MaChuyen", "tChuyenDuLich", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "FK_tDangKy_MaKhach", "tKhach")]
        public tKhach tKhach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tKhach>("ModelQLDKDL.FK_tDangKy_MaKhach", "tKhach").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tKhach>("ModelQLDKDL.FK_tDangKy_MaKhach", "tKhach").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tKhach> tKhachReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tKhach>("ModelQLDKDL.FK_tDangKy_MaKhach", "tKhach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tKhach>("ModelQLDKDL.FK_tDangKy_MaKhach", "tKhach", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelQLDKDL", Name="tDiaDiemThamQuan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tDiaDiemThamQuan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tDiaDiemThamQuan object.
        /// </summary>
        /// <param name="maDD">Initial value of the MaDD property.</param>
        public static tDiaDiemThamQuan CreatetDiaDiemThamQuan(global::System.String maDD)
        {
            tDiaDiemThamQuan tDiaDiemThamQuan = new tDiaDiemThamQuan();
            tDiaDiemThamQuan.MaDD = maDD;
            return tDiaDiemThamQuan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaDD
        {
            get
            {
                return _MaDD;
            }
            set
            {
                if (_MaDD != value)
                {
                    OnMaDDChanging(value);
                    ReportPropertyChanging("MaDD");
                    _MaDD = StructuralObject.SetValidValue(value, false, "MaDD");
                    ReportPropertyChanged("MaDD");
                    OnMaDDChanged();
                }
            }
        }
        private global::System.String _MaDD;
        partial void OnMaDDChanging(global::System.String value);
        partial void OnMaDDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenDD
        {
            get
            {
                return _TenDD;
            }
            set
            {
                OnTenDDChanging(value);
                ReportPropertyChanging("TenDD");
                _TenDD = StructuralObject.SetValidValue(value, true, "TenDD");
                ReportPropertyChanged("TenDD");
                OnTenDDChanged();
            }
        }
        private global::System.String _TenDD;
        partial void OnTenDDChanging(global::System.String value);
        partial void OnTenDDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTinhThanh
        {
            get
            {
                return _TenTinhThanh;
            }
            set
            {
                OnTenTinhThanhChanging(value);
                ReportPropertyChanging("TenTinhThanh");
                _TenTinhThanh = StructuralObject.SetValidValue(value, true, "TenTinhThanh");
                ReportPropertyChanged("TenTinhThanh");
                OnTenTinhThanhChanged();
            }
        }
        private global::System.String _TenTinhThanh;
        partial void OnTenTinhThanhChanging(global::System.String value);
        partial void OnTenTinhThanhChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "tChiTietTuyenDuLich", "tChuyenDuLich")]
        public EntityCollection<tChuyenDuLich> tChuyenDuLich
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tChuyenDuLich>("ModelQLDKDL.tChiTietTuyenDuLich", "tChuyenDuLich");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tChuyenDuLich>("ModelQLDKDL.tChiTietTuyenDuLich", "tChuyenDuLich", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelQLDKDL", Name="tKhach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tKhach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tKhach object.
        /// </summary>
        /// <param name="maKhach">Initial value of the MaKhach property.</param>
        public static tKhach CreatetKhach(global::System.String maKhach)
        {
            tKhach tKhach = new tKhach();
            tKhach.MaKhach = maKhach;
            return tKhach;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaKhach
        {
            get
            {
                return _MaKhach;
            }
            set
            {
                if (_MaKhach != value)
                {
                    OnMaKhachChanging(value);
                    ReportPropertyChanging("MaKhach");
                    _MaKhach = StructuralObject.SetValidValue(value, false, "MaKhach");
                    ReportPropertyChanged("MaKhach");
                    OnMaKhachChanged();
                }
            }
        }
        private global::System.String _MaKhach;
        partial void OnMaKhachChanging(global::System.String value);
        partial void OnMaKhachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKhach
        {
            get
            {
                return _TenKhach;
            }
            set
            {
                OnTenKhachChanging(value);
                ReportPropertyChanging("TenKhach");
                _TenKhach = StructuralObject.SetValidValue(value, true, "TenKhach");
                ReportPropertyChanged("TenKhach");
                OnTenKhachChanged();
            }
        }
        private global::System.String _TenKhach;
        partial void OnTenKhachChanging(global::System.String value);
        partial void OnTenKhachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DienThoai
        {
            get
            {
                return _DienThoai;
            }
            set
            {
                OnDienThoaiChanging(value);
                ReportPropertyChanging("DienThoai");
                _DienThoai = StructuralObject.SetValidValue(value, true, "DienThoai");
                ReportPropertyChanged("DienThoai");
                OnDienThoaiChanged();
            }
        }
        private global::System.String _DienThoai;
        partial void OnDienThoaiChanging(global::System.String value);
        partial void OnDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "FK_tDangKy_MaKhach", "tDangKy")]
        public EntityCollection<tDangKy> tDangKy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tDangKy>("ModelQLDKDL.FK_tDangKy_MaKhach", "tDangKy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tDangKy>("ModelQLDKDL.FK_tDangKy_MaKhach", "tDangKy", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelQLDKDL", Name="tTuyen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tTuyen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tTuyen object.
        /// </summary>
        /// <param name="maTuyen">Initial value of the MaTuyen property.</param>
        public static tTuyen CreatetTuyen(global::System.String maTuyen)
        {
            tTuyen tTuyen = new tTuyen();
            tTuyen.MaTuyen = maTuyen;
            return tTuyen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaTuyen
        {
            get
            {
                return _MaTuyen;
            }
            set
            {
                if (_MaTuyen != value)
                {
                    OnMaTuyenChanging(value);
                    ReportPropertyChanging("MaTuyen");
                    _MaTuyen = StructuralObject.SetValidValue(value, false, "MaTuyen");
                    ReportPropertyChanged("MaTuyen");
                    OnMaTuyenChanged();
                }
            }
        }
        private global::System.String _MaTuyen;
        partial void OnMaTuyenChanging(global::System.String value);
        partial void OnMaTuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTuyen
        {
            get
            {
                return _TenTuyen;
            }
            set
            {
                OnTenTuyenChanging(value);
                ReportPropertyChanging("TenTuyen");
                _TenTuyen = StructuralObject.SetValidValue(value, true, "TenTuyen");
                ReportPropertyChanged("TenTuyen");
                OnTenTuyenChanged();
            }
        }
        private global::System.String _TenTuyen;
        partial void OnTenTuyenChanging(global::System.String value);
        partial void OnTenTuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoNgay
        {
            get
            {
                return _SoNgay;
            }
            set
            {
                OnSoNgayChanging(value);
                ReportPropertyChanging("SoNgay");
                _SoNgay = StructuralObject.SetValidValue(value, "SoNgay");
                ReportPropertyChanged("SoNgay");
                OnSoNgayChanged();
            }
        }
        private Nullable<global::System.Int32> _SoNgay;
        partial void OnSoNgayChanging(Nullable<global::System.Int32> value);
        partial void OnSoNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true, "GhiChu");
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelQLDKDL", "FK_tChuyenDuLich_MaTuyen", "tChuyenDuLich")]
        public EntityCollection<tChuyenDuLich> tChuyenDuLich
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tChuyenDuLich>("ModelQLDKDL.FK_tChuyenDuLich_MaTuyen", "tChuyenDuLich");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tChuyenDuLich>("ModelQLDKDL.FK_tChuyenDuLich_MaTuyen", "tChuyenDuLich", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
