//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVeDuLich
    {
        public string MaVe { get; set; }
        public string TenTour { get; set; }
        public Nullable<System.DateTime> NgayKHanh { get; set; }
        public string PhuongTien { get; set; }
        public Nullable<double> GiaVe { get; set; }
        public string MaKhach { get; set; }
    
        public virtual tKhach tKhach { get; set; }
    }
}
